services:
  api:
    build: .
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DB_DRIVER=${DB_DRIVER:-mongo}
      - MONGO_URI=mongodb://mongo:27017/devosphere-core
      - PG_URI=postgres://postgres:postgres@postgres:5432/devosphere
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TTL_DAYS=7
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - postgres
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devosphere
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  mongo_data:
  pg_data:

